In [3]:
import numpy as np
y = np.array([1,2,3])
x = np.array([2,3,4])
x + y

array([3, 5, 7])

In [4]:
x - y

array([1, 1, 1])

In [5]:
x / y

array([2.        , 1.5       , 1.33333333])

In [6]:
np.dot(x,y)

20

In [7]:
x * y

array([ 2,  6, 12])

In [8]:
a = np.array(
[[2,3],
 [2,3]])
b = np.array(
[[3,4],
 [5,6]])

In [9]:
np.dot(a,b)

array([[21, 26],
       [21, 26]])

In [10]:
a*b

array([[ 6, 12],
       [10, 18]])

In [11]:
a.T

array([[2, 2],
       [3, 3]])

In [13]:
a = np.array([
 [1, 2]
 ])

In [14]:
a.shape

(1, 2)

In [15]:
a = np.array(
[[2,3],
 [2,3]])
b = np.array(
[[3,4],
 [5,6]])

In [16]:
a.shape

(2, 2)

In [17]:
b.shape

(2, 2)

In [18]:
a = np.array([
 [1, 2]
 ])

In [20]:
mm = np.dot(a,b)

In [21]:
mm

array([[13, 16]])

In [22]:
mm.shape

(1, 2)